### ISSUE TITLE
Unifying / generalizing the implementation of checkpoints / compliance (time-dependent parameters)

### ISSUE THREAD

**Issue by jorisvandenbossche** [UGentBiomath/COVID19-Model#141]
Currently, the interface to define checkpoints and how those values change through time is somewhat complex to use (especially in optimization).

On the one hand, the user can specify checkpoints like this:

```python
# Create checkpoints dictionary
chk = {
    't':  [60, 120], 
    'Nc': [..., ....]
}
# Run simulation
y = model.sim(total_time, checkpoints=chk)
```

The checkpoint value is given at simulation time, is not a "parameter" as the others, complicating the optimization code. For example, currently some checkpoint values are hardcoded inside the `MLE` definition at https://github.com/UGentBiomath/COVID19-Model/blob/6df47288c11f27ca0aff43b743487a4d3b4542d5/src/covid19model/optimization/objective_fcns.py#L158 

(which is to be able to include the `prevention` parameter in the optimization, where `prevention` determines the values inside the checkpoints dictionary)

But in addition, you can also control *how* the transition from one value to the other (at a checkpoint) goes, using eg a smoother ramp than a simple "jump" in the value. This is done by specifying a `compliance` function at model initialization:

```python
from covid19model.models.compliance import ramp_2
# Initialize the model
model = models.COVID19_SEIRD(initial_states, params, compliance=ramp_2)
```

This compliance function can have additional parameters, and those are automatically added to the model parameters (and can thus also be optimized like other parameters), and has a specific signature (`func(t_since_last_chkp, old, new, **kwargs`).

So to summarize, I think this has some drawbacks:

- The values in the checkpoint dictionary are hard to change as parameter (both the time at which they happen as the value to change to)
- Both the checkpoint as the compliance function together determine the exact value of the parameter in question (typically the interaction matrix), but are defined in two different places (and the interaction is ensure by passing "time since last checkpoint" to the compliance function, putting the responsibility of keeping track of this in the core base model)

---

A possible alternative, that combines both aspects in one, would be to provide the option to specify a *single function* that can control *time-dependent variables*. 

So you could have something like the following (exact keyword names to be discussed, it would be nice to have something shorter as `time_dependent_parameters` ..):

```python

def my_interaction_matrix_evolution(t, param_init, prevention, tau, ...):
    ....
    # use prevention, tau, ... kwargs together with the time to determine interaction matrix
    return Nc

# on model initialization, you specify that this function needs to be used for the Nc parameter of the model
model = models.COVID19_SEIRD(
    initial_states, params, time_dependent_parameters={'Nc': my_interaction_matrix_evolution}
)

# Run simulation doesn't need to pass a checkpoint (this is embodied in the function passed at init)
y = model.sim(total_time)
```

Similarly as with the current `compliance` function, the additional keyword arguments of the time-dependent parameter function can automatically (with some validation) be added to the model's parameter dictionary. And this way, all the checkpoint/compliance-related parameters can be optimized as a normal parameter (so also `prevention`).

For the simple case of just specifying a checkpoints dictionary (without compliance function), the above would be a bit more complex, but we could provide a helper function that turns a checkpoints dictionary into a function with the correct signature and behaviour. Because in the end, the equivalent function for a simple checkpoint `{'t': [t0, t1], 'Nc': [val0, val1]}` is something like:

```python
def func_from_checkpoint(time, param_init):
    if time < t0:
        return param_init
    elif t0 <= time < t1:
        return val0
    else:
        return val1
``` 

so it would be relatively straightforward to generate such a function based on a checkpoints dictionary.

cc @twallema @JennaVergeynst @stijnvanhoey thoughts?

**Comment by JennaVergeynst** [comment]
Sounds good to me. This would also allow to have other parameters changing over time, if need be (for instance hospital residence times appeared to be decreasing during the first peak, due to improved care)

**Comment by twallema** [comment]
Overall this sounds like a big improvement from the current implementation.

One potential drawback is that for every change in a checkpoint, a time-dependent function must be coded in the backend and the model must be reinitialized. For instance, if you want to run two scenarios in a notebook, you'd have to define two time-dependent functions in a helper file (f.i. `utils.py` or a dedicated file). Then, in each notebook cell, the model must be reinitialized before running the simulation. We must thus be aware that we're going to sacrificing a little 'user-friendliness' with this change, as functionality is moved from front-end to back-end. However, I personally don't find this a big issue (because I know the code and am thus very biased :+1: ). What do you think?

**Comment by JennaVergeynst** [comment]
I think in most cases, the helper function (turning a checkpoint dictionary into a function) will be sufficient, and only exceptionally it would be needed to create new functions. And also reinitializing the model does not seem too big an issue for me neither!
