### ISSUE TITLE
Propose general layout for repository

### ISSUE THREAD

**Issue by stijnvanhoey** [UGentBiomath/COVID19-Model#25]
@JennaVergeynst  In order to support further developments, a more rigid structure of the repository code and some agreed standards (e.g. name conventions) would probably be beneficial.

Inspired by [cookiecutter for data science](https://drivendata.github.io/cookiecutter-data-science/), but taking into account the type of modelling dealing with, I would like to propose the following structure:

```
.
## data

├── data                                    <- cfr. current set of data sets
│   ├── interaction_matrices
│   │   ├── ...
│   │   └── USA
│   ├── interim                             <- data sets after speicific manipulation
│   │   ├── Age pyramid of Belgium.csv
│   │   ├── contacts.Rdata
│   │   ├── imperialCollegeAgeDist.csv
│   │   └── incubation.csv
│   ├── raw                                 <- data as provided in raw format
│   │   └── ...
│   └── README.md                  <- for each data set: what, how to get,...

## code

├── covid                                       <- all reusable code blocks 
│   ├── __init__.py                         <- structured as lightweight python package
│   ├── data                                   <- any code required for data manipulation (raw -> interim)
│   │   └── DataExtraction.ipynb    <- should probably better be a *.py script
│   ├── models                               <- code for models. Usage will be: `from covid.models import ...`
│   │   ├── coronaHelper2.py
│   │   ├── economic_model.py
│   │   └── models.py
│   ├── optimization                       
│   │   └── pso.py
│   ├── tests
│   │   └── tests_CG.py
│   └── visualization                   
│   │   └── ...
├── setup.py                                  <- structured as lightweight python package

## documentation (sphinx folder layout as example)

├── docs                                         <- documentation 
│   ├── _build
│   ├── conf.py
│   ├── index.rst/index.md              <- explanations are written inside markdown or st files
│   ├── models.md                          <- models get in-depth descriptions in docs
│   ├── make.bat
│   ├── Makefile
│   ├── _static
│   │   └── figs                                 <- figs linked to the documentation
│   │       ├── ...
│   │       └── SEIRSNetworkModel.jpg
│   └── _templates

## HPC specific code

├── hpc
│   ├── calibrate_stochastic.py
│   ├── README.md
│   ├── sim_stochastic.py
│   └── test.sh

## notebooks

├── notebooks                               <- notebooks are collected here, we need name convention(!)
│   ├── EconomicModel.ipynb
│   ├── [Experimental] Calibation of Age-Structured deterministic model (2).ipynb
│   ├── [MPC] Linked-In part two.ipynb
│   └── templates                           <- demo notebooks that can be used as starting point (and binder intro)
│       ├── SEIRSAgeModel_demo.ipynb
│       └── SEIRSNetworkModel_demo.ipynb

├── reports                                 <- optional (e.g. report from automatic daily rerun)
│   └── figures

## automate stuff

├── .github                                 <- Automate specific steps with github actions
│   ├── workflows
│   │   ├── dataload.yml             <- e.g. automate data load from sciensano
│   │   └── docs.yml                   <- e.g. make sure documentation is up to date

## other info

├── LICENSE
├── environment.yml
└── README.md                                <- focus on how to get started, setup environment name conventions and structure of the repo
```

Some notes:

- The simultaneous development of `mycode.py` in python files and notebook code is supported by having a `develop` install of the code in combination with the `%load_ext autoreload` notebook mgic function. This will be documented in the `README.md` getting started
- The documentation will contain both the info on the code itself (classes, functions, methods) as well as the model descriptions currently all written in the general `README.md`. Either [sphinx](https://www.sphinx-doc.org/en/master/) or another tool can be used, but sphinx is the Python default and with the nbsphinx and recommonmark extensions we can support respectively jupyter notebook and markdown files as source of the documentation.
- it will be important to have clear guidelines on the structure of the data folder and having descriptions on where each of them is coming from and how to update/.. a data set.
- For the package code, probably a good idea to use the [PEP8](https://www.python.org/dev/peps/pep-0008/) guidelines.
- We can see how far we get with the `github/workflows` to automate data/analysis steps, as this does not require to setup separate infrastructure or services. 

After having this setup and some guidelines, we can start splitting apart the code itself into a set of modules/functionalities.

When we do transform to this kind of structure, it will certainly break some code (e.g. references to data sets in notebooks), but I do think this is currently still manageable. I extracted the folder tree above from [my fork](https://github.com/stijnvanhoey/COVID19-Model).

Input is certainly welcome. @Beramos @jorisvandenbossche

**Comment by Beramos** [comment]
Thanks for putting in so much effort. I fully agree with this but I was kind of procrastinating this change, since the technical level of most collaborators is not that high and I wanted to avoid people being overwhelmed by the repo structure. However, I do think this change should be done now since there are quite a lot of new people that will join this effort in the near future. @twallema can we make this drastic change in structure of the repository?

**Comment by JennaVergeynst** [comment]
Thanks @stijnvanhoey.
Maybe something to keep in mind: there will be a "spatial extension" of the model at some point, by the group of Jan Baetens. (i.e. for each agglomeration a model, and the interactions in-between). I guess this should become also part of this github then. But I think this could be fit in under "models".

**Comment by twallema** [comment]
@stijnvanhoey Thanks so many times for the input! @Beramos You can make the change. Should we package the current code as the 'second version' and denote the changes by Stijn as the 'third version'? What we have so far works so maybe it would be good to have it 'handy'.

**Comment by Beramos** [comment]
@twallema, ok! it might indeed be a good idea to package the current code

**Comment by twallema** [comment]
Current code has been packaged as v2.0.

**Comment by Beramos** [comment]
@stijnvanhoey  can you give some pointers on how to use the `develop` install for the python code?

**Comment by jorisvandenbossche** [comment]
>  can you give some pointers on how to use the develop install for the python code?

Once the python code is put in a separate directory as a python package (+ a `setup.py` file), you can do `pip install --editable .` from the root of the repo, and then the latest version of the package will always be available in the python environment in which you installed it (so that when making changes to the code in `covid/models/...py`, you don't have to reinstall the package each time).

**Comment by stijnvanhoey** [comment]
I added this information to the documentation website in #35.

**Comment by stijnvanhoey** [comment]
I do think this issue can be closed, new layout is up and running.

**Comment by Beramos** [comment]
This can be closed, I thought I already closed this via a pull request

Op di 26 mei 2020 12:08 schreef Stijn Van Hoey <notifications@github.com>:
