### ISSUE TITLE
[function realTimeScenario] Visualistation of uncertainty band on model prediction

### ISSUE THREAD

**Issue by twallema** [UGentBiomath/COVID19-Model#30]
**Description of problem:**

[Disclaimer] This is a highly technical problem.

The incubation time is Erlang distributed with an average of 5.2 days and a relatively long tail. (95% of people experience symptoms within 12 days). The deterministic and network model handle this uncertainty in a different manner. The deterministic implementation uses a Monte-Carlo approach to handle the uncertainty of the incubation period. The model is simulated 1000 times and each time a sample is drawn from the distribution function of the incubation period. After these 1000 simulations, the average and 10-90 percentiles are visualized. The network model incorporates this uncertainty in a completely different and much more elegant way. Each node in the network is assigned an incubation period that was sampled straight from the distribution function. The model is simulated a couple of times to account for the stochastic nature of the model (usually 10 times) and afterward, the average and 10-90 percentiles are visualized.

A problem arises with the **deterministic model**. During the initial days of the outbreak, the disease transmission is exponential in nature. This makes the predicted outbreak outcome after government measures extremely sensitive to the exact day they were taken. When looking at the number of ICU beds occupied for Belgium, this peaked at 1200 beds occupied. On the one hand, if the measures were taken a couple of days later, the maximum ICU capacity would have surely been surpassed. On the other hand, if measures were taken a bit earlier, the number of ICU beds occupied at the height of the pandemic would have been much lower.

An incubation period is a form of latency from policy to hospitalization curve. When introducing a stepwise change in policy, the effect of a 1-day incubation period vs a 12-day incubation period on the hospitalization curve is huge. When performing Monte-Carlo sampling, this represents a major problem because uncertainty bands are too broad. A visual example of the problem is included in the /figs subdirectory as *monteCarloProblem.png*.

What we would ideally want to accomplish is not visualizing the uncertainty band up until the present day. Then, starting in the future, the uncertainty band can actually be visualized. Normally, this should be an easy fix, but unfortunately, the way parameters are changed using *checkpoints dictionaries* prohibits this. The function *realTimeScenario* works as follows,

1. The *checkpoints dictionary* containing the past government policies and the future government policies are merged into one *checkpoints dictionary*.
2. An incubation period is sampled from the distribution.
3. The simulation is run over the full length of the past + the future using the merged *checkpoints dictionary*.
4. Steps 2-3 are repeated 1000 times.
5. Average and 10-90 percentiles are visualized.

While ideally, the workflow would work as follows,

1. The checkpoints dictionary containing the past policies is used to simulate the model. Monte-Carlo sampling is enabled but only the average is visualized.
2. The final model prediction (representing "today") is used as an initial condition to simulate the future.
3. The checkpoints dictionary containing future policies is used to simulate the model. Monte Carlo sampling is enabled and the average + percentiles are visualized.

**Proposed solution:**
This model shortcoming can be solved by either rethinking the way the model generates output or by rethinking the visualization functions. The latter could potentially be solved as follows: Currently, the SEIRSAgeModel stores its output in a 3D matrix, where the X-axis is equal to the number of age bins (1 for no-age layering, 16 when using the interaction matrices), the Y-axis is equal to the simulation time 0 to the maximum simulation time in steps of 1 day, and the different Monte-Carlo simulations are stored along the Z-axis. An idea could be to checkpoint a variable *monteCarloVisualisation*. As long as this variable is *False*, the model could calculate the average along the Z-axis and replace all entries along the Z-axis with the average. If the *monteCarloVisualisation* set to *True*, the different model outcomes during Monte-Carlo sampling are left "as is".

**Comment by JennaVergeynst** [comment]
Problem solved, I guess? Current visualisation of uncertainty seems fully legitimate to me.
