### ISSUE TITLE
Issue templates: Contact information for non-code questions

### ISSUE THREAD

**Issue by stijnvanhoey** [UGentBiomath/COVID19-Model#33]
I propose to have people working on the code and having issues with it post their issues here. 

However, I do think it would be useful to add some information in the [ISSUE_TEMPLATE](https://github.com/stijnvanhoey/COVID19-Model/blob/cookiecutter/.github/ISSUE_TEMPLATE.md) on who to contact or what to do for more model-specific questions not related to code/implementation. 

An issue template is what people see as a template when opening a new issue, https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

@JennaVergeynst can you provide some input?

**Comment by JennaVergeynst** [comment]
I think at this moment @twallema is still the best person to contact for model-specific questions... Do you want me to provide input in the issue_template directly?

**Comment by stijnvanhoey** [comment]
That's fine to me. You can change the content directly as you please.

**Comment by Beramos** [comment]
Maybe it is a good idea to make two issue-templates, one for technical issues and non-technical questions with the respective information available in both templates.  @JennaVergeynst I changed your role to maintainer so you should have  access to configure issue templates.

**Comment by JennaVergeynst** [comment]
Added a section on content-related questions to the issue-template
