### ISSUE TITLE
Exclude hardcoded refs to data files

### ISSUE THREAD

**Issue by stijnvanhoey** [UGentBiomath/COVID19-Model#34]
e.g. `'../data/incubation.csv'`: https://github.com/UGentBiomath/COVID19-Model/blob/master/src/models.py#L448

`https://github.com/UGentBiomath/COVID19-Model/blob/master/src/models.py#L1358`

**Comment by jorisvandenbossche** [comment]
In addition to those hardcoded data files, the parameter values and initial values of variables that are not read from a file are also re-defined in multiple places (eg in multiple places in the notebooks).

It might be good to centralize those (at least for the "default" values), and import/read them in the notebook, so there is a single places where those values are defined (and can be documented).

**Comment by JennaVergeynst** [comment]
I think this has been fixed now, with the function to read parameters? So I guess we can close this?
