### ISSUE TITLE
xarray representation of model outputs

### ISSUE THREAD

**Issue by stijnvanhoey** [UGentBiomath/COVID19-Model#45]
To represent the model output (and actually the model itself), we will use [xarray](http://xarray.pydata.org/en/stable/index.html) as it fits with the representation of our model output (multi-N array with labels):

- time `T`
- multiple repetitions (e.g. monte-carlo simulations,...) `N`
- multiple variables `V`
- stratification (coming from the interactions) `S`

By saving the parameters as xarray attributes, we have the model as such for later re-use: initial conditions are the first elements of the variables, the time vector has the time output of a simulation and the parameter values in the attributes. e.g. dumped as netcdf this makes it easier to share or reuse.

We can save a model output as either a xarray `DataArray` or xarray `Dataset`:

as `DataArray`:

```
dim time (T), dim states (S) and stratification (N)  + dim MC samples

occurrences: S x N x T
```
    
as `Dataset` with the different states as

```
dim time (T) and stratification (N)  + dim MC samples

stratified
S: N x T
I: N x T
... 
```
(without stratification in e.g. age the N dimension is 1)

@jorisvandenbossche  and @stijnvanhoey will try out these options with respect to the plotting

**Comment by stijnvanhoey** [comment]
We will use the `Dataset` layout with each state defined as a variable. 
When the model is stratified, the dimensions are `time` AND `stratification`,

![image](https://user-images.githubusercontent.com/754862/83412034-bd94ba80-a419-11ea-9270-46dd24f33b07.png)

when the model is not stratified, only the dimension 'time' and dropping the `stratification` dimension.

![image](https://user-images.githubusercontent.com/754862/83412161-f3d23a00-a419-11ea-95f0-2a830967c708.png)



Going from stratified to not-stratified is linked by summing over the stratification dimension:  `.sum(dim="stratified")`

**Comment by stijnvanhoey** [comment]
For the stratified, plotting as ine plot requires the `to_array()` method:

```
output.sum(dim="stratification")[["S", "I", "E", "R"]].to_array().plot.line(x='time');
```

**Comment by stijnvanhoey** [comment]
@twallema could you have a quick  look at this if this would work for you as well? 

The main difference is that you get more a _pandas_like feeling when requesting data as the states get labels. For example, selecting a single a variable is 

```
output["S"]
```
instead of `output[0, :]`. Or making an aggregation along the stratification becomes:

```
output.sum(dim="stratification")
```
instead of `np.sum(output, axis=1)`. Hence, a bit more writing, but much more declaritive. Moreover, in the backend is everything still numpy, so always possible to switch. 

With respect, for example, the main plotting functions like `plotPopulation` and `plotInfected`, the interface would not really change, see https://github.com/stijnvanhoey/COVID19-Model/blob/refactor/src/covid19model/visualization/output.py but it provides us to make models more self-containing and the code descriptive.

**Comment by twallema** [comment]
This will be good for third party users, it's intuitive!

**Comment by twallema** [comment]
Is time is called 'time' or 't'?

**Comment by stijnvanhoey** [comment]
I would opt for `time` instead of `t`.

**Comment by twallema** [comment]
Okay, np! This looks really good ;) Can I suggest `age` as a shorter version for `stratification`? Normally there's no confusion with other parameters.

**Comment by stijnvanhoey** [comment]
Well, the concept is more general in the sense that the interaction matrix could represent any set of groups and not just a stratification on age. Could be for example 'school - working - retired' 3x3 matrix as well and the same implementation should work. That's why we opted for a more general term. Still, other suggestions are welcome

**Comment by jorisvandenbossche** [comment]
> That's why we opted for a more general term. Still, other suggestions are welcome

We can maybe add a "stratification name", so you can indicate your stratification dimension should be called that way.

**Comment by JennaVergeynst** [comment]
I guess we're full into and agreeing about xarrays, so I'm closing this issue ;-)
