### ISSUE TITLE
clarification on numpy docstirng

### ISSUE THREAD

**Issue by stijnvanhoey** [UGentBiomath/COVID19-Model#48]
@twallema as requested about the docsring format, documentation on numpy docstring format is available [here](https://numpydoc.readthedocs.io/en/latest/format.html). Make sure to have  a short description, `parameters` and `returns` always provided, optionally also other useful information (eg in `notes`).

As an example, your sciensana function (it has no input parameters) could be something like:

__Note__ I would adjust the function and return a tuple instead of the list with a list (this is just a proposal as in your example you already do unpacking, but you'll get the point)

```
def get_sciensano_data():
    """Download Sciensano hospitalisation cases data 

    This function downloads and updates the available data on hospitalisation cases (including ICU).

    Returns
    -----------
    index : pd.DatetimeIndex
        datetimes for which a data point is available
    initial :  str 'YYYY-MM-DD'
        initial date of records as string
    ICU : np.array
        total number of hospitalised patients in ICU
    hospital : np.array
        total number of hospitalised patients

    Notes
    --------
    The data is extracted from Sciensano database: https://epistat.wiv-isp.be/covid/
    Data is reported as showed in: https://epistat.sciensano.be/COVID19BE_codebook.pdf

    Examples
    --------------
    >>> index, initial, ICU, hospital = get_sciensano_data()
    """
    
    ...
    return index, initial, ICU, hospital
```

Using it as a tuple makes unpacking rather easy when using the function: `index, initial, ICU, hospital = get_sciensano_data()`. Still up to your preference and mainly serving as example.

**Comment by twallema** [comment]
@stijnvanhoey `google.py` and `sciensano.py` have been documented in this way. Both functions now save a copy of the downloaded data to the /data/raw.

**Comment by stijnvanhoey** [comment]
nice work, thanks. Closing this issue.
