### ISSUE TITLE
'ICU' is both parameter as well as variable name

### ISSUE THREAD

**Issue by stijnvanhoey** [UGentBiomath/COVID19-Model#49]
When checking the code to try out the refactoring as described in https://github.com/UGentBiomath/COVID19-Model/issues/42, I noticed `ICU` is used both as [parameter](https://github.com/UGentBiomath/COVID19-Model/blob/master/src/covid19model/models/models.py#L224) as well as [variable](https://github.com/UGentBiomath/COVID19-Model/blob/master/src/covid19model/models/models.py#L228). As such, `ICU` takes the value of the variable.

I assume the `ICU` as parameter should probably be `maxICU` instead, as it is [initialized](https://github.com/UGentBiomath/COVID19-Model/blob/master/src/covid19model/models/models.py#L87) in the class? But I do not really see where the value of `maxICU` is actually used.

@twallema could you maybe clarify this?

**Comment by twallema** [comment]
`maxICU` is a relic from past implementations that can be removed.

**Comment by stijnvanhoey** [comment]
ok, thanks. And what about the parameter `ICU' as input of the `system_dfes` on [line 224](https://github.com/UGentBiomath/COVID19-Model/blob/master/src/covid19model/models/models.py#L224)? Can also be removed?
