### ISSUE TITLE
Package/model not available in binder

### ISSUE THREAD

**Issue by Beramos** [UGentBiomath/COVID19-Model#59]
As suggested in #55 by @stijnvanhoey 

Indeed, good point. Moreover, the step of `pip install -e`. should be included as well during setup to make sure the package/model itself is available inside the notebooks.

The latter issue on the `pip install -e` we can probably fix by adding a postBuild configuration file inside binder folder, see binder docs

**Comment by jorisvandenbossche** [comment]
If there is a setup.py, it should also install the package, according to https://mybinder.readthedocs.io/en/latest/config_files.html#setup-py-install-python-packages 
Although I don't know if that works "additive" to environment.yml, or only one of both is used.

**Comment by Beramos** [comment]
It is very cryptic

**Comment by Beramos** [comment]
The suggestion by @stijnvanhoey in #55 worked: adding a postBuild script to pip install the COVID model
