### ISSUE TITLE
unclear purpose of the "templates" folder in notebooks folder 

### ISSUE THREAD

**Issue by Beramos** [UGentBiomath/COVID19-Model#61]
@twallema what is the idea of the templates folder?

**Comment by twallema** [comment]
@stijnvanhoey or @jorisvandenbossche made this modification. The goal was to group the "demo" notebooks in this folder because they're a good starting point to start coding.

**Comment by Beramos** [comment]
And what are the notebooks outside this folder

Op vr 29 mei 2020 17:33 schreef twallema <notifications@github.com>:

**Comment by twallema** [comment]
Economic model --> frontend for development of economic model
[Experimental] Calibation of Age-Structured deterministic model (2) --> old relic, but may still contain some usefull stuff
[MPC] Linked-In part two --> old relic, but may still contain some usefull stuff
SCRATCH_MCMC --> learned how to work with MCMC. can be removed in future

**Comment by Beramos** [comment]
I'm going to close this, when reading the docs it is pretty clear what the templates folder is about
