### ISSUE TITLE
Duplicate notebook SEIRSNetworkModel_demo

### ISSUE THREAD

**Issue by Beramos** [UGentBiomath/COVID19-Model#64]
There seems to be a rogue notebook in the [src folder](https://github.com/UGentBiomath/COVID19-Model/blob/master/src/SEIRSNetworkModel_demo.ipynb)

It should be there but It seems that it might be more up to date than its twin in the [notebooks folder](https://github.com/UGentBiomath/COVID19-Model/blob/master/notebooks/SEIRSNetworkModel_demo.ipynb)

Which one should we keep?

**Comment by JennaVergeynst** [comment]
@twallema I guess this notebook shouldn't be in the source folder. Good if I move it to notebooks?

**Comment by twallema** [comment]
Yes, thanks Jenna!

**Comment by JennaVergeynst** [comment]
Thanks @Beramos
