### ISSUE TITLE
**Documentation: How to use the model**

### ISSUE THREAD

**Issue by Beramos** [UGentBiomath/COVID19-Model#72]
[link](https://ugentbiomath.github.io/COVID19-Model/application)

Add a description of:
- [ ] SEIRSAgeModel_demo
- [ ] SEIRSNetworkModel_demo
- [ ] ageStratified_scenarios

**Comment by JennaVergeynst** [comment]
@twallema still need for this, or is the current description sufficient?

**Comment by twallema** [comment]
@JennaVergeynst The demo should be sufficient.
