### ISSUE TITLE
**Docs: Background**

### ISSUE THREAD

**Issue by Beramos** [UGentBiomath/COVID19-Model#73]
[link](https://ugentbiomath.github.io/COVID19-Model/models.html#)

This part of the docs is a bit sloppy
- [ ] improve typesetting

**Comment by JennaVergeynst** [comment]
Seems that equation rendering is not supported. @jorisvandenbossche can you fix that?

**Comment by JennaVergeynst** [comment]
Fixed by Joris, @Beramos I think we can close this issue?

**Comment by Beramos** [comment]
It looks beautiful! :) Thank you!
