### ISSUE TITLE
sphinx build location depends on used command

### ISSUE THREAD

**Issue by stijnvanhoey** [UGentBiomath/COVID19-Model#76]
mmm, I do think we were a bit fast on merging #70 . I did a recheck:

- `python setup.py build_sphinx` -> cfr. CI creates the docs by default in `build/sphinx/html`
- `make html` -> creates the docs by default in `docs/_build/html`

So we should probably pick one or the other to document.

@Beramos or @jorisvandenbossche any preference?

**Comment by jorisvandenbossche** [comment]
>  creates the docs by default in docs/_build/html

This is the default of sphinx, so if we choose one, I think that would be better. 

But is that something you can configure with setuptools' sphinx integration?

**Comment by Beramos** [comment]
To not overcomplicate things and avoid changing the github action shall we just use `python setup.py build_sphinx` and remove the make HTML option? It is not that one of the options is easier since all dependencies must be installed for both I presume?

**Comment by jorisvandenbossche** [comment]
Yes, that's certainly fine as well
