### ISSUE TITLE
function `get_COVID19_SEIRD_parameters` not working due to missing file

### ISSUE THREAD

**Issue by stijnvanhoey** [UGentBiomath/COVID19-Model#91]
@JennaVergeynst I tried to use the `get_COVID19_SEIRD_parameters` function, but I do think `abrams_etal.csv` is not available, but `wu_etal` is.

**Comment by JennaVergeynst** [comment]
Yes sorry, changed the name, didn't change the code :-) Will fix it

**Comment by JennaVergeynst** [comment]
Fixed and also updated the data readme. Thanks for noticing!

**Comment by stijnvanhoey** [comment]
@JennaVergeynst I do think `BELagedist_10year.txt` is also missing?

**Comment by stijnvanhoey** [comment]
> @JennaVergeynst I do think `BELagedist_10year.txt` is also missing?

my mistake, I used wrong rel path...

__Note__ I had to change the rel-paths to make it work from an other notebook location than `templates` folder, https://github.com/UGentBiomath/COVID19-Model/pull/92/files#diff-82c9e271fbb734fba0aa380d5254b3d1 (part of #92)
