### ISSUE TITLE
Clarify figure of model dynamics

### ISSUE THREAD

**Issue by JennaVergeynst** [UGentBiomath/COVID19-Model#99]
@twallema I think it would be useful to add all "flow" parameters to the overview of model dynamics (for instance here: https://ugentbiomath.github.io/COVID19-Model/models.html). Now it only shows sigma and beta... could you add the parameters to the other arrows as well? Makes it easier to link with equations

**Comment by twallema** [comment]
@danillana has made a nice looking figure in tikz (LaTeX).

**Comment by JennaVergeynst** [comment]
@twallema , I added the latest flowchart figure to the webpage referred to above. This page still requires to be updated with the latest (final) model dynamics however. Can you do so?

**Comment by JennaVergeynst** [comment]
Thanks @twallema , I'm closing this now!
